apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
      - name: kubedemoapp
      image: vyshitha/sample:kubeimage2
      imagePullPolicy: Always
      ports:
        - containerPort: 5001
